### ISSUE TITLE
Can OpenSSL name be more than 64 characters?

### ISSUE THREAD

**Issue by Shokrian** [aws/aws-rfdk#1038]
### Environment

  - **CDK CLI Version      :**
  - **CDK Framework Version:**
  - **RFDK Version:**
  - **Deadline Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by Shokrian** [comment]
Can OpenSSL name be more than 64 characters?

**Comment by Shokrian** [comment]
Please help me to solve the following error problem.
problems making Certificate Request
3555938678416:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:158:maxsize=64

**Comment by ddneilson** [comment]
Duplicate of: https://github.com/aws/aws-rfdk/issues/1039
