### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by koenverwimp** [aws/aws-rfdk#105]
Step 10 of this readme is not correct. This is a copy paste issue from the TypeScript documentation:
https://github.com/aws/aws-rfdk/blob/mainline/examples/deadline/All-In-AWS-Infrastructure-Basic/python/README.md

**Comment by ddneilson** [comment]
Thanks for reaching out. I agree that it looks weird to see a command for a Node.js tool in the middle of a README for a Python application, but that's actually not an error.  You'll see the same in our developer guide here: https://docs.aws.amazon.com/rfdk/latest/guide/first-rfdk-app.html#stage-docker-recipes

The reason for the strangeness is that our `stage-deadline` command-line tool is currently only available in the Node.js package for the RFDK, so you have to use `npx` to run that command from the Node.js package. We are working on bringing that command-line tool into the Python package for RFDK, but we're not there yet.

**Comment by jusiskin** [comment]
I think @koenverwimp might be referring to the references to modifying `package.json`. Those shouldn't be there.

**Comment by koenverwimp** [comment]
Yes, it does look strange to me that i have to configure the deadline version in the package.json and as an environment variable? Even if it so, it's not clear.  The first RFDK app doesn't mention anything about package.json, and seems to work without it.

**Comment by koenverwimp** [comment]
I think the "bin/config.py" should as well be "package/config.py".

**Comment by ddneilson** [comment]
> 
> 
> I think the "bin/config.py" should as well be "package/config.py".

Ah, right you are! Thanks for pointing that out.

**Comment by koenverwimp** [comment]
According to the documentation I have to add my UsageBasedLicenses

"5. Choose your UBL limits and change the value of the ubl_licenses variable in bin/config.py accordingly:
self.ubl_licenses: List[UsageBasedLicense] = [<your-ubl-limits> (e.g. UsageBasedLicense.forMaya(10))] "

It needs to be "UsageBasedLicense.for_maya(10)" in python.

PS: your example is still pointing to aws-rfdk version 0.16.0

**Comment by jusiskin** [comment]
Thanks for pointing this out and helping fix this for those that follow in your footsteps. I'll put together a follow-up PR for these new findings.

**Comment by koenverwimp** [comment]
It would also be great if there was any explanation how to connect with Deadline Monitor to the RCS fleet. Or did i miss something in the documentation? I guess i need to create a PFX file from certificates that i can find in AWS secret manager? But i didnt get it to work so far.

**Comment by jusiskin** [comment]
> It would also be great if there was any explanation how to connect with Deadline Monitor to the RCS fleet. 

Agreed - this is important documentation that is missing. I've created a separate issue (#110) to track this.

**Comment by jusiskin** [comment]
Re-opening this. #106 auto-closed this after merge, but UBL issue was not addressed
