### ISSUE TITLE
MountableEFS.mountToLinuxInstance causes all future userdata commands to not run

### ISSUE THREAD

**Issue by grbartel** [aws/aws-rfdk#117]
When you run the method MountableEFS.mountToLinuxInstance it adds user datacommand to download the file mountEfs.sh.  It then executes this code to perform the mounting.  The last line in this file is `exit $?`, since this script is being run in the same shell as the main Userdata and not it's own subshell this exits the entire userdata shell causing all lines after it in the userdata to not execute.

In order to fix this we need to either:

1. Run mountEfs.sh in a subshell
1. Remove the call to exit from mountEFS.

### Reproduction Steps

This can be reproduced by doing the following:
1. Create a MountableEFS file system
1. Create an instance
1. Call `fs.mount_to_linux_instance(instance)`
1. Call `instance.user_data.add_commands(<your commands here>)`
1. Deploy your app and see if the extra commands run.

### Error Log

I am seeing the User data exit before running my additional commands

### Environment

  - **CDK CLI Version      :*1.57.0*
  - **CDK Framework Version:*1.57.0*
  - **RFDK Version:*0.17*
  - **Deadline Version:*10.1.9.2*

--- 

This is :bug: Bug Report

**Comment by ddneilson** [comment]
Could not reproduce. Test case:
```
    const bastion = new ec2.BastionHostLinux(this, 'Bastion', {
      vpc: props.vpc,
      availabilityZone,
    });

    const fileSystem = new rfdk.MountableEfs(this, {
      filesystem: new efs.FileSystem(this, 'EfsFileSystem', {
        vpc: props.vpc,
        encrypted: true,
        removalPolicy: cdk.RemovalPolicy.DESTROY,
      }),
    });

    fileSystem.mountToLinuxInstance(bastion.instance, {
      location: '/mnt/efs',
    });

    bastion.instance.userData.addCommands('echo "We got past the mount" > ~ec2-user/file.out');
```

Results in the 'file.out' file being created as expected. 

The mount script is definitely running in a subshell -- https://github.com/aws/aws-rfdk/blob/90c83a4dcafa06c66b2d66cc37d4e2b554c6c7d5/packages/aws-rfdk/lib/core/lib/mountable-efs.ts#L98 -- so, something else must have been going on.
