### ISSUE TITLE
Incorrect Katana and Maxwell Usage-Based Licensing Port

### ISSUE THREAD

**Issue by jusiskin** [aws/aws-rfdk#123]
The `aws-rfdk.deadline.UsageBasedLicense.forKatana()` method adds a security group ingress rule for port 4101, when the licensing traffic for Katana is actually served on port 4151.

Similarly, `aws-rfdk.deadline.UsageBasedLicense.forKatana()` adds a rule for port 5055 but should be 5555.

--- 

This is :bug: Bug Report

**Comment by ddneilson** [comment]
@jusiskin Thanks for the report, Josh. Where did you get the port 4151 information from? Both our internal files for Usage Based Licensing and the public licensing documentation for Katana (https://learn.foundry.com/katana/Content/ug/installation_licensing/licensing_linux.html ) reference port 4101.

edit: I read the internal files wrong. Though Katana's license server listens on 4101, Deadline's Usage Based Licensing listens on 4151 and forwards that to 4101 on the license server.
