### ISSUE TITLE
Add linting for whitespace in TypeScript type declarations

### ISSUE THREAD

**Issue by jusiskin** [aws/aws-rfdk#132]
Currently, the linters configured in the code repository do not lint for consistent whitespace between TypeScript variable names and their type declaration.

For example, all of the following whitespace usages are accepted:

```ts
const myVar:string;
const myVar: string;
const myvar:       string;
```

Similarly, function and class method argument declarations are not linted:

```ts
class Foo {
  constructor(a:string) {
  }
}
class Foo {
  constructor(a: string) {
  }
}
class Foo {
  constructor(a:    string) {
  }
}
```

This issue proposes adding/configuring the linters to check whitespace in such cases.

### Use Case

Without linting, code style can become inconsistent between different files. It also causes unnecessary cycles in code review. This issue originates from a [code review discussion](https://github.com/aws/aws-rfdk/pull/118#discussion_r492246231) that had the contributor change all of their whitespace only to later discover that the change made their code inconsistent with the rest of the repository's codebase. Having proper linting for this code style removes enforces this code style convention before code review and makes the convention easily discovered by new contributors or to prior contributors if we decide to change the convention.

### Proposed Solution

Investigate the various linters we use in the project and determine if any support this type of linting. If so, configure the linter and apply the style to any non-compliant source files. If not, investigate the possibility of creating a linter rule for this.

### Other

N/A

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by grbartel** [comment]
This should just involving adding the rule "@typescript-eslint/type-annotation-spacing" with default settings to our eslintrc.js file

see: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/type-annotation-spacing.md
