### ISSUE TITLE
Create a Construct to supply Deadline installers

### ISSUE THREAD

**Issue by horsmand** [aws/aws-rfdk#176]
We would like a construct which determines the S3 URI's for the Deadline installers and Deadline Docker recipes. The version of Deadline for these can be either specified by the user or defaulted to the latest version.

For now, this will be integrated with the Repository construct to get the repository installer for it to use. In the future we can extend it out to be used by other constructs that require Deadline installers or the Docker recipes as well.

### Use Case

Currently to get the repository installer, we use hard-coded values that make assumptions about where the installer should be found in S3:
https://github.com/aws/aws-rfdk/blob/75d0f9fedce52de9dcfe73482965de923fa8941d/packages/aws-rfdk/lib/deadline/lib/version.ts#L293-L310

This would provide a more robust way of determining the installer locations

### Proposed Solution

A VersionQuery Construct that contains a CustomResource that downloads the [version index file](https://downloads.thinkboxsoftware.com/version_info.json) and parses it, then returns the required information about the installers for a specific Deadline version.

The Repository construct will then take the versioned installers supplied by the VersionQuery construct, and use the repo installer.

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by zxkane** [comment]
Any plan to mirror the deadline installers to other aws partitions?

**Comment by jusiskin** [comment]
@zxkane - Thanks for reaching out! I've taken your feature request and made a separate issue (#207).
