### ISSUE TITLE
Configurable expiry for generated X.509 certificates

### ISSUE THREAD

**Issue by ddneilson** [aws/aws-rfdk#241]
All X.509 certificates generated by the `X509CertificatePem` construct have a default expiry of 3 years, and that is not configurable. The request is to make that expiry configurable.

### Use Case

Prevent render farms from becoming inoperable after 3 years by extending the duration of X.509 certificates.

### Other

N/A

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by horsmand** [comment]
Implemented by #242
