### ISSUE TITLE
Create deadline group/pool implicitly while configuring SEP

### ISSUE THREAD

**Issue by yashda** [aws/aws-rfdk#358]
After creating and configuring a spot fleet via RFDK constructs `SpotEventPluginFleet` & `ConfigureSpotEventPlugin`, there is a requirement for manually creating deadline groups and pools before the spot fleet request can be created.
Details [here](https://docs.aws.amazon.com/rfdk/api/latest/docs/aws-rfdk.deadline.ConfigureSpotEventPlugin.html)

This can be done by either
1. Running a deadline command to create group/pool, or,
2. Creating group/pool using deadline monitor.

This manual stop of creating the deadline groups/pools can be automated while deployment.

### Use Case

With this feature, once a farm is deployed by the user, the only step required by an user to start using the spot fleet is to submit a job for this deadline group.

### Proposed Solution

In order to eliminate this manual step of creating group/pool, an additional call can be made to RCS to automatically create the deadline group for which the spot request is being configured.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ddneilson** [comment]
Note: Group/Pool names in Deadline *must* be lower-case.
