### ISSUE TITLE
On-Demand worker fleets time out during deployment if min_capacity is set to 0

### ISSUE THREAD

**Issue by aws-painec** [aws/aws-rfdk#442]
Deploying a CDK application with an On-Demand worker fleet that has its min_capacity set to zero will result in the ASG timing out and the deployment failing.

### Reproduction Steps
1. Launch an EC2 instance with the latest version of Nimble StudioBuilder
2. Create a valid configuration for a studio. Add an On-Demand worker fleet (OS shouldn't matter) and set its minimum instance capacity to 0
3. Deploy the studio

(Launching a more limited application with just the worker fleet would almost certainly repro the same issue, but I haven't tested that myself)

### Error Log

```
2021-05-24 13:25:45 UTC-0700 | WorkerFleetondemandlinuxASG254059E0 | &nbsp;
CREATE_FAILED | Received 0 SUCCESS signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```

### Environment

  - **CDK CLI Version  :** 1.99.0
  - **CDK Framework Version:**
  - **RFDK Version:** 0.30.0
  - **Deadline Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

I believe I've found the root cause of the issue:

[Here](https://github.com/aws/aws-rfdk/blob/mainline/packages/aws-rfdk/lib/deadline/lib/worker-fleet.ts#L461) is where the RFDK defines on-demand worker fleets. Note that it will always set `resourceSignalTimeout`

But as the [CDK documentation](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_autoscaling/AutoScalingGroup.html) notes for the `resourceSignalCount` field:
>  How many ResourceSignal calls CloudFormation expects before the resource is considered created. Default: 1 if resourceSignalTimeout is set, 0 otherwise

Because the timeout is always being set, the ASG will *always* expect one instance to send a resource signal when it completes. But if min capacity is zero, then there's no instance, and no signal, and the ASG times out.

--- 

This is :bug: Bug Report

**Comment by ddneilson** [comment]
Fix would be to not set https://github.com/aws/aws-rfdk/blob/e7eddea0c37b143b2eed7db7ed62a42960cac95e/packages/aws-rfdk/lib/deadline/lib/worker-fleet.ts#L461 & https://github.com/aws/aws-rfdk/blob/e7eddea0c37b143b2eed7db7ed62a42960cac95e/packages/aws-rfdk/lib/deadline/lib/worker-fleet.ts#L517 if the minimum/desired count is 0.

Trade-off is that by doing so, the customer will not know if there's a configuration error until they try to deploy workers. Right now, a configuration error will result in the Cfn stack failing to deploy. With the proposed change a misconfiguration will result in a successful stack deployment; worker nodes would spin up when requested, but failures would only detectable by looking at the worker logs.
