### ISSUE TITLE
Unsafe Yaml load

### ISSUE THREAD

**Issue by ddneilson** [aws/aws-rfdk#444]
Just a general security improvement. We use Python's `yaml.load()` when configuring the MongoDB instance. The input to this is the stock `/etc/mongod.conf` as installed by the MongoDB installer. To be paranoid, we should be using `yaml.safe_load()` instead -- `yaml.load()` can execute any Python code that exists in the configuration file.

### Environment

  - **CDK CLI Version      :** Any
  - **CDK Framework Version:** Any
  - **RFDK Version:** 0.32.0
  - **Deadline Version:** Any
  - **Node.js Version:** Any
  - **OS               :** Any
  - **Language (Version):** All

--- 

This is :bug: Bug Report

**Comment by jusiskin** [comment]
This was resolved in #445
