### ISSUE TITLE
Repository fails to update if repository_settings conflict 

### ISSUE THREAD

**Issue by matta-aws** [aws/aws-rfdk#460]
Updating a Repository fails if repository_settings already exist.

Using [deadlinecommand to import repository settings](https://docs.thinkboxsoftware.com/products/deadline/10.1/1_User%20Manual/manual/repository-settings-importer-exporter.html?highlight=importrepositorysettings#importing-repository-settings) errors if a setting already exists in the database (if using the Append import-type)

When updating a rfdk Repository, that error causes the cdk deploy to fail and rollback.

### Reproduction Steps

create a file, "settings.json" with a path mapping rule, such as:
```
{ "PathMapping": { "Version": 1, "Settings": {
      "GlobalRules": [{
          "Path": "X:",
          "WindowsPath": "X:",
          "LinuxPath": "/foo/bar"}]  
}}}
```
use  those settings for the repository
```
settings = aws-cdk.s3_assets.Asset(self, "Settings", path="settings.json")
repo=aws-rfdk.deadline.Repsoitory(
   ...
   repository_settings=settings
)
```
Deploy once to build the repository  (confirm path mappings were set)
Change the Deadline version (as the repository installer will not run if it detects the version is the same) then redeploy.

### Error Log

cdk deploy fails with an AutoScalingGroup error:
```
UPDATE_FAILED        | AWS::AutoScaling::AutoScalingGroup          | Repository/Installer/ASG
Received 1 FAILURE signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```

in the logs, it shows the path map conflict:
```
Problem running post-install step. Installation may not complete correctly
 An error occurred while trying to import the repository settings: Import was unsuccessful. The following errors occured while handling the request: 
{
  "PathMapping": [
    "Error: The repository already contains a Path Mapping Rule for path 'X:' in region 'all'."
  ]
}
```

### Environment

  - **CDK CLI Version      :** 1.106.1
  - **CDK Framework Version:**
  - **RFDK Version:** 0.33.0
  - **Deadline Version:** 10.1.14 -> 10.1.15
  - **Node.js Version:**  v12.22.1
  - **OS               :**
  - **Language (Version):**  Pyhon 3.7.9

### Other

--- 

This is :bug: Bug Report

**Comment by jericht** [comment]
Thanks for pointing this out! This has been fixed in Deadline 10.1.17 (see [release notes](https://docs.thinkboxsoftware.com/products/deadline/10.1/1_User%20Manual/manual/release-notes.html)). Users can upgrade their farms to at least Deadline 10.1.17 and won't see this issue anymore.
