### ISSUE TITLE
Implement using Construct.construct to stay ahead of deprecation of Construct.node

### ISSUE THREAD

**Issue by ddneilson** [aws/aws-rfdk#55]
Upstream CDK has deprecated the use of `Construct.node` in favor of `Construct.construct`. We'll need to update places where we access through `Construct.node` to use `Construct.construct` instead.

Reference: https://github.com/aws/aws-cdk/pull/9557/

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jusiskin** [comment]
It appears that this was reverted in aws/aws-cdk#9637 (CDK v1.58.0+) due to aws/jsii#1880. I discussed this with the CDK core team and it sounds like they are sticking with `.node` for the foreseeable future.

Closing this issue.
